// This file is auto-generated by openapi-typescript.
// Do not edit this file manually.

export interface paths {
  '/health': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              status: string;
              version: string;
              instance_fqdn: string;
            };
          };
        };
      };
    };
  };
  '/channels': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': Array<{
              id: string;
              name: string;
              description?: string;
              instance_fqdn: string;
              max_participants: number;
              current_participants: number;
              created_at: string;
              updated_at: string;
            }>;
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          'application/json': {
            name: string;
            description?: string;
            max_participants?: number;
          };
        };
      };
      responses: {
        201: {
          content: {
            'application/json': {
              id: string;
              name: string;
              description?: string;
              instance_fqdn: string;
              max_participants: number;
              current_participants: number;
              created_at: string;
              updated_at: string;
            };
          };
        };
      };
    };
  };
} 