/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChannelNameRouteImport } from './routes/$channelName'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstanceFqdnChannelNameRouteImport } from './routes/$instanceFqdn/$channelName'

const ChannelNameRoute = ChannelNameRouteImport.update({
  id: '/$channelName',
  path: '/$channelName',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstanceFqdnChannelNameRoute = InstanceFqdnChannelNameRouteImport.update({
  id: '/$instanceFqdn/$channelName',
  path: '/$instanceFqdn/$channelName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$channelName': typeof ChannelNameRoute
  '/$instanceFqdn/$channelName': typeof InstanceFqdnChannelNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$channelName': typeof ChannelNameRoute
  '/$instanceFqdn/$channelName': typeof InstanceFqdnChannelNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$channelName': typeof ChannelNameRoute
  '/$instanceFqdn/$channelName': typeof InstanceFqdnChannelNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$channelName' | '/$instanceFqdn/$channelName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$channelName' | '/$instanceFqdn/$channelName'
  id: '__root__' | '/' | '/$channelName' | '/$instanceFqdn/$channelName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelNameRoute: typeof ChannelNameRoute
  InstanceFqdnChannelNameRoute: typeof InstanceFqdnChannelNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$channelName': {
      id: '/$channelName'
      path: '/$channelName'
      fullPath: '/$channelName'
      preLoaderRoute: typeof ChannelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$instanceFqdn/$channelName': {
      id: '/$instanceFqdn/$channelName'
      path: '/$instanceFqdn/$channelName'
      fullPath: '/$instanceFqdn/$channelName'
      preLoaderRoute: typeof InstanceFqdnChannelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelNameRoute: ChannelNameRoute,
  InstanceFqdnChannelNameRoute: InstanceFqdnChannelNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
