/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import the component files

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ChannelNameImport } from './routes/$channelName'
import { Route as InstanceFqdnChannelNameImport } from './routes/$instanceFqdn/$channelName'

// Create/Update Routes

const IndexRoute = IndexImport
const ChannelNameRoute = ChannelNameImport
const InstanceFqdnChannelNameRoute = InstanceFqdnChannelNameImport

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$channelName': {
      id: '/$channelName'
      path: '/$channelName'
      fullPath: '/$channelName'
      preLoaderRoute: typeof ChannelNameImport
      parentRoute: typeof rootRoute
    }
    '/$instanceFqdn/$channelName': {
      id: '/$instanceFqdn/$channelName'
      path: '/$instanceFqdn/$channelName'
      fullPath: '/$instanceFqdn/$channelName'
      preLoaderRoute: typeof InstanceFqdnChannelNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ChannelNameRoute,
  InstanceFqdnChannelNameRoute,
})

/* prettier-ignore-end */ 