/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestAuthRouteImport } from './routes/test-auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChannelNameRouteImport } from './routes/$channelName'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstanceFqdnChannelNameRouteImport } from './routes/$instanceFqdn/$channelName'
import { Route as GroupNameChannelNameRouteImport } from './routes/$groupName/$channelName'
import { Route as InstanceFqdnGroupNameChannelNameRouteImport } from './routes/$instanceFqdn/$groupName/$channelName'

const TestAuthRoute = TestAuthRouteImport.update({
  id: '/test-auth',
  path: '/test-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelNameRoute = ChannelNameRouteImport.update({
  id: '/$channelName',
  path: '/$channelName',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstanceFqdnChannelNameRoute = InstanceFqdnChannelNameRouteImport.update({
  id: '/$instanceFqdn/$channelName',
  path: '/$instanceFqdn/$channelName',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupNameChannelNameRoute = GroupNameChannelNameRouteImport.update({
  id: '/$groupName/$channelName',
  path: '/$groupName/$channelName',
  getParentRoute: () => rootRouteImport,
} as any)
const InstanceFqdnGroupNameChannelNameRoute =
  InstanceFqdnGroupNameChannelNameRouteImport.update({
    id: '/$instanceFqdn/$groupName/$channelName',
    path: '/$instanceFqdn/$groupName/$channelName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$channelName': typeof ChannelNameRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/test-auth': typeof TestAuthRoute
  '/$groupName/$channelName': typeof GroupNameChannelNameRoute
  '/$instanceFqdn/$channelName': typeof InstanceFqdnChannelNameRoute
  '/$instanceFqdn/$groupName/$channelName': typeof InstanceFqdnGroupNameChannelNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$channelName': typeof ChannelNameRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/test-auth': typeof TestAuthRoute
  '/$groupName/$channelName': typeof GroupNameChannelNameRoute
  '/$instanceFqdn/$channelName': typeof InstanceFqdnChannelNameRoute
  '/$instanceFqdn/$groupName/$channelName': typeof InstanceFqdnGroupNameChannelNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$channelName': typeof ChannelNameRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/test-auth': typeof TestAuthRoute
  '/$groupName/$channelName': typeof GroupNameChannelNameRoute
  '/$instanceFqdn/$channelName': typeof InstanceFqdnChannelNameRoute
  '/$instanceFqdn/$groupName/$channelName': typeof InstanceFqdnGroupNameChannelNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$channelName'
    | '/admin'
    | '/settings'
    | '/setup'
    | '/test-auth'
    | '/$groupName/$channelName'
    | '/$instanceFqdn/$channelName'
    | '/$instanceFqdn/$groupName/$channelName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$channelName'
    | '/admin'
    | '/settings'
    | '/setup'
    | '/test-auth'
    | '/$groupName/$channelName'
    | '/$instanceFqdn/$channelName'
    | '/$instanceFqdn/$groupName/$channelName'
  id:
    | '__root__'
    | '/'
    | '/$channelName'
    | '/admin'
    | '/settings'
    | '/setup'
    | '/test-auth'
    | '/$groupName/$channelName'
    | '/$instanceFqdn/$channelName'
    | '/$instanceFqdn/$groupName/$channelName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelNameRoute: typeof ChannelNameRoute
  AdminRoute: typeof AdminRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TestAuthRoute: typeof TestAuthRoute
  GroupNameChannelNameRoute: typeof GroupNameChannelNameRoute
  InstanceFqdnChannelNameRoute: typeof InstanceFqdnChannelNameRoute
  InstanceFqdnGroupNameChannelNameRoute: typeof InstanceFqdnGroupNameChannelNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-auth': {
      id: '/test-auth'
      path: '/test-auth'
      fullPath: '/test-auth'
      preLoaderRoute: typeof TestAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$channelName': {
      id: '/$channelName'
      path: '/$channelName'
      fullPath: '/$channelName'
      preLoaderRoute: typeof ChannelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$instanceFqdn/$channelName': {
      id: '/$instanceFqdn/$channelName'
      path: '/$instanceFqdn/$channelName'
      fullPath: '/$instanceFqdn/$channelName'
      preLoaderRoute: typeof InstanceFqdnChannelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$groupName/$channelName': {
      id: '/$groupName/$channelName'
      path: '/$groupName/$channelName'
      fullPath: '/$groupName/$channelName'
      preLoaderRoute: typeof GroupNameChannelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$instanceFqdn/$groupName/$channelName': {
      id: '/$instanceFqdn/$groupName/$channelName'
      path: '/$instanceFqdn/$groupName/$channelName'
      fullPath: '/$instanceFqdn/$groupName/$channelName'
      preLoaderRoute: typeof InstanceFqdnGroupNameChannelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelNameRoute: ChannelNameRoute,
  AdminRoute: AdminRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TestAuthRoute: TestAuthRoute,
  GroupNameChannelNameRoute: GroupNameChannelNameRoute,
  InstanceFqdnChannelNameRoute: InstanceFqdnChannelNameRoute,
  InstanceFqdnGroupNameChannelNameRoute: InstanceFqdnGroupNameChannelNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
