/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all channels */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Channel"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new channel */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreateChannelRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Channel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/id/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific channel by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Channel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific channel by name */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Channel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_name}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a voice channel */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["JoinChannelRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Participant"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_name}/rtp-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get router RTP capabilities */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RtpCapabilities"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_name}/transports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create WebRTC transport */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreateTransportRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["TransportInfo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/{transport_id}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect WebRTC transport */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transport_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ConnectTransportRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/{transport_id}/produce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start producing media */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transport_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ProduceRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ProduceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/{transport_id}/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start consuming media */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transport_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ConsumeRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ConsumeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_name}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get channel participants */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Participant"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update participant media state */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    participant_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ParticipantUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": unknown;
                    };
                };
            };
        };
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login/registration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserAuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["User"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/{user_id}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's joined channels */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ChannelMembershipWithChannel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_instance_fqdn}/{channel_name}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get channel members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_instance_fqdn: string;
                    channel_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        /** Join a channel (become a member) */
        post: {
            parameters: {
                query: {
                    user_id: string;
                };
                header?: never;
                path: {
                    channel_instance_fqdn: string;
                    channel_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ChannelMembership"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_instance_fqdn}/{channel_name}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Leave a channel (remove membership) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_instance_fqdn: string;
                    channel_name: string;
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start WebAuthn registration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["RegisterBeginRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RegisterBeginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish WebAuthn registration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["RegisterFinishRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RegisterFinishResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start WebAuthn authentication */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["LoginBeginRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LoginBeginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish WebAuthn authentication */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["LoginFinishRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["LoginFinishResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's credentials */
        get: {
            parameters: {
                query: {
                    user_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["CredentialInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/credentials/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user's credential */
        delete: {
            parameters: {
                query: {
                    user_id: string;
                };
                header?: never;
                path: {
                    credential_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get instance settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["InstanceSettings"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update instance settings (admin only) */
        patch: {
            parameters: {
                query: {
                    admin_user_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["UpdateInstanceSettingsRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["InstanceSettings"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all invitations for instance (admin only) */
        get: {
            parameters: {
                query: {
                    admin_user_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["InvitationWithCreator"][];
                    };
                };
            };
        };
        put?: never;
        /** Create an invitation */
        post: {
            parameters: {
                query: {
                    user_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreateInvitationRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Invitation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invitations/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's invitations */
        get: {
            parameters: {
                query: {
                    user_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Invitation"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invitations/{invitation_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate an invitation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    invitation_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": boolean;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an invitation */
        delete: {
            parameters: {
                query: {
                    _user_id: string;
                };
                header?: never;
                path: {
                    invitation_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": boolean;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{invite_code}/use": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Use an invitation to register */
        post: {
            parameters: {
                query: {
                    user_id: string;
                };
                header?: never;
                path: {
                    invite_code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Invitation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{invite_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invitation details by code (for registration page) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    invite_code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Invitation"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users for instance (admin only) */
        get: {
            parameters: {
                query: {
                    admin_user_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Channel */
        Channel: {
            /** Format: uuid */
            channel_id: string;
            name: string;
            description?: string;
            instance_fqdn: string;
            /** Format: uuid */
            group_id: string;
            /** Format: int32 */
            max_participants: number;
            /** Format: int32 */
            current_participants: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** ChannelMembership */
        ChannelMembership: {
            /** Format: uuid */
            membership_id: string;
            /** Format: uuid */
            user_id: string;
            channel_instance_fqdn: string;
            channel_name: string;
            /** Format: date-time */
            joined_at: string;
            /** Format: date-time */
            last_active: string;
        };
        /** ChannelMembershipWithChannel */
        ChannelMembershipWithChannel: {
            /** Format: uuid */
            membership_id: string;
            /** Format: uuid */
            user_id: string;
            channel_instance_fqdn: string;
            channel_name: string;
            /** Format: date-time */
            joined_at: string;
            /** Format: date-time */
            last_active: string;
            channel?: components["schemas"]["Channel"];
        };
        /** ConnectTransportRequest */
        ConnectTransportRequest: {
            transport_id: string;
            dtls_parameters: components["schemas"]["DtlsParameters"];
        };
        /** ConsumeRequest */
        ConsumeRequest: {
            transport_id: string;
            producer_id: string;
            rtp_capabilities: components["schemas"]["RtpCapabilities"];
        };
        /** ConsumeResponse */
        ConsumeResponse: {
            consumer_id: string;
            producer_id: string;
            kind: string;
            rtp_parameters: unknown;
        };
        /** CreateChannelRequest */
        CreateChannelRequest: {
            name: string;
            description?: string;
            /** Format: uuid */
            group_id: string;
            /** Format: int32 */
            max_participants?: number;
        };
        /** CreateInvitationRequest */
        CreateInvitationRequest: {
            /** Format: int32 */
            max_uses?: number;
            /** Format: date-time */
            expires_at?: string;
            invited_email?: string;
        };
        /** CreateTransportRequest */
        CreateTransportRequest: {
            producing: boolean;
            consuming: boolean;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            username: string;
        };
        /** CredentialInfo */
        CredentialInfo: {
            /** Format: uuid */
            credential_record_id: string;
            name?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string;
        };
        /** DtlsFingerprint */
        DtlsFingerprint: {
            algorithm: string;
            value: string;
        };
        /** DtlsParameters */
        DtlsParameters: {
            role: string;
            fingerprints: components["schemas"]["DtlsFingerprint"][];
        };
        /** IceCandidate */
        IceCandidate: {
            foundation: string;
            /** Format: uint32 */
            priority: number;
            ip: string;
            /** Format: uint16 */
            port: number;
            type: string;
            protocol: string;
        };
        /** IceParameters */
        IceParameters: {
            username_fragment: string;
            password: string;
        };
        /** InstanceSettings */
        InstanceSettings: {
            /** Format: uuid */
            settings_id: string;
            instance_fqdn: string;
            registration_mode: string;
            invite_permission: string;
            /** Format: int32 */
            invite_limit?: number;
            instance_name: string;
            instance_description?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** Invitation */
        Invitation: {
            /** Format: uuid */
            invitation_id: string;
            invite_code: string;
            /** Format: uuid */
            created_by: string;
            /** Format: uuid */
            invited_by?: string;
            invited_email?: string;
            instance_fqdn: string;
            /** Format: int32 */
            max_uses?: number;
            /** Format: int32 */
            current_uses: number;
            is_active: boolean;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            used_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** InvitationWithCreator */
        InvitationWithCreator: {
            invitation: components["schemas"]["Invitation"];
            creator_username: string;
            creator_display_name: string;
        };
        /** JoinChannelRequest */
        JoinChannelRequest: {
            user_id: string;
        };
        /** LoginBeginRequest */
        LoginBeginRequest: Record<string, never>;
        /** LoginBeginResponse */
        LoginBeginResponse: {
            challenge_id: string;
            options: unknown;
        };
        /** LoginFinishRequest */
        LoginFinishRequest: {
            challenge_id: string;
            credential: unknown;
        };
        /** LoginFinishResponse */
        LoginFinishResponse: {
            /** Format: uuid */
            user_id: string;
            username: string;
            success: boolean;
        };
        /** Participant */
        Participant: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            channel_id: string;
            user_id: string;
            peer_id: string;
            display_name: string;
            is_audio_enabled: boolean;
            is_video_enabled: boolean;
            /** Format: date-time */
            joined_at: string;
        };
        /** ParticipantUpdate */
        ParticipantUpdate: {
            is_audio_enabled?: boolean;
            is_video_enabled?: boolean;
        };
        /** ProduceRequest */
        ProduceRequest: {
            transport_id: string;
            kind: string;
            rtp_parameters: unknown;
        };
        /** ProduceResponse */
        ProduceResponse: {
            producer_id: string;
        };
        /** RegisterBeginRequest */
        RegisterBeginRequest: {
            display_name: string;
            invite_code?: string;
        };
        /** RegisterBeginResponse */
        RegisterBeginResponse: {
            challenge_id: string;
            options: unknown;
        };
        /** RegisterFinishRequest */
        RegisterFinishRequest: {
            challenge_id: string;
            credential: unknown;
        };
        /** RegisterFinishResponse */
        RegisterFinishResponse: {
            /** Format: uuid */
            user_id: string;
            success: boolean;
        };
        /** RtpCapabilities */
        RtpCapabilities: {
            codecs: components["schemas"]["RtpCodecCapability"][];
            header_extensions: components["schemas"]["RtpHeaderExtension"][];
        };
        /** RtpCodecCapability */
        RtpCodecCapability: {
            kind: string;
            mime_type: string;
            /** Format: uint32 */
            clock_rate: number;
            /** Format: uint32 */
            channels?: number;
            parameters: unknown;
        };
        /** RtpHeaderExtension */
        RtpHeaderExtension: {
            uri: string;
            /** Format: uint32 */
            id: number;
        };
        /** TransportInfo */
        TransportInfo: {
            id: string;
            ice_parameters: components["schemas"]["IceParameters"];
            ice_candidates: components["schemas"]["IceCandidate"][];
            dtls_parameters: components["schemas"]["DtlsParameters"];
        };
        /** UpdateInstanceSettingsRequest */
        UpdateInstanceSettingsRequest: {
            registration_mode?: string;
            invite_permission?: string;
            /** Format: int32 */
            invite_limit?: number;
            instance_name?: string;
            instance_description?: string;
        };
        /** UpdateUserRequest */
        UpdateUserRequest: {
            display_name?: string;
            is_admin?: boolean;
        };
        /** User */
        User: {
            /** Format: uuid */
            user_id: string;
            username: string;
            display_name: string;
            instance_fqdn: string;
            is_admin: boolean;
            has_passkey: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** UserAuthResponse */
        UserAuthResponse: {
            user: components["schemas"]["User"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
