name: "publish"

on:
  workflow_dispatch:
#   push:
#     branches:
#       - release

jobs:
  publish-electron:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            dist: "pnpm dist --mac"
          - platform: "ubuntu-22.04"
            dist: "pnpm dist --linux"
          - platform: "windows-latest"
            dist: "pnpm dist --win"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools rpm

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
    
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: install frontend dependencies
        run: pnpm config set auto-install-peers false && pnpm install

      - name: build desktop packages
        run: ${{ matrix.dist }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
